"""Tests verifying Python graph/DSL operations match Dafny formal specifications.

Auto-generated by scripts/generate_dafny_conformance_tests.py from:
  - src/dafny/dag.dfy
  - src/dafny/do_calculus.dfy
  - src/dafny/probability.dfy

Do not edit manually. Re-run the generator to update.
"""

import unittest

from y0.algorithm.conditional_independencies import are_d_separated
from y0.algorithm.do_calculus import (
    rule_1_of_do_calculus_applies,
    rule_2_of_do_calculus_applies,
    rule_3_of_do_calculus_applies,
    satisfies_backdoor,
    satisfies_frontdoor,
)
from y0.dsl import Variable
from y0.graph import NxMixedGraph


class TestSurgeryLemmas(unittest.TestCase):
    """Tests corresponding to dag.dfy §4 Graph Surgery lemmas."""

    def setUp(self) -> None:
        """Build the three-node chain A -> B -> C from dag.dfy §9."""
        self.A = Variable("A")
        self.B = Variable("B")
        self.C = Variable("C")
        self.chain = NxMixedGraph.from_edges(
            directed=[(self.A, self.B), (self.B, self.C)]
        )

    def test_remove_incoming_empty_is_identity(self):
        """RemoveIncoming(G, {}) == G.

        Ref: dag.dfy:139 RemoveIncoming_Empty
        """
        self.assertEqual(self.chain, self.chain.remove_in_edges(set()))

    def test_remove_incoming_no_parents_for_target(self):
        """Nodes in X lose all parents after incoming surgery.

        Ref: dag.dfy:148 RemoveIncoming_NoParents
        """
        mutilated = self.chain.remove_in_edges({self.B})
        self.assertEqual(set(), set(mutilated.directed.predecessors(self.B)))

    def test_remove_incoming_preserves_others(self):
        """Nodes outside X keep their parents after incoming surgery.

        Ref: dag.dfy:154 RemoveIncoming_PreservesOthers
        """
        mutilated = self.chain.remove_in_edges({self.B})
        self.assertEqual({self.B}, set(mutilated.directed.predecessors(self.C)))

    def test_remove_outgoing_empty_is_identity(self):
        """RemoveOutgoing(G, {}) == G.

        Ref: dag.dfy:160 RemoveOutgoing_Empty
        """
        self.assertEqual(self.chain, self.chain.remove_out_edges(set()))

    def test_remove_outgoing_removes_children(self):
        """Nodes in X lose all children after outgoing surgery.

        Ref: dag.dfy RemoveOutgoing definition (dual of RemoveIncoming_NoParents)
        """
        mutilated = self.chain.remove_out_edges({self.B})
        self.assertEqual(set(), set(mutilated.directed.successors(self.B)))

    def test_remove_outgoing_preserves_others(self):
        """Nodes outside X keep their children after outgoing surgery.

        Ref: dag.dfy RemoveOutgoing definition (dual of RemoveIncoming_PreservesOthers)
        """
        mutilated = self.chain.remove_out_edges({self.B})
        self.assertEqual({self.B}, set(mutilated.directed.successors(self.A)))

    def test_remove_incoming_also_removes_bidirected(self):
        """RemoveIncoming on ADMG also removes bidirected edges to X.

        Ref: ADMG extension of dag.dfy RemoveIncoming (Dafny models directed-only)
        """
        graph = NxMixedGraph.from_edges(
            directed=[(self.A, self.B), (self.B, self.C)],
            undirected=[(self.A, self.B)],
        )
        mutilated = graph.remove_in_edges({self.B})
        self.assertEqual(set(), set(mutilated.directed.predecessors(self.B)))
        self.assertEqual(set(), set(mutilated.undirected.neighbors(self.B)))


class TestAncestryLemmas(unittest.TestCase):
    """Tests corresponding to dag.dfy §2-3 Acyclicity and Ancestry."""

    def setUp(self) -> None:
        """Build the three-node chain A -> B -> C from dag.dfy §9."""
        self.A = Variable("A")
        self.B = Variable("B")
        self.C = Variable("C")
        self.chain = NxMixedGraph.from_edges(
            directed=[(self.A, self.B), (self.B, self.C)]
        )

    def test_ancestor_reflexive(self):
        """Every node is its own ancestor.

        Ref: dag.dfy Ancestor_Reflexive
        """
        for node in [self.A, self.B, self.C]:
            self.assertIn(node, self.chain.ancestors_inclusive(node))

    def test_ancestor_transitive(self):
        """Ancestry is transitive: A ancestor of B, B ancestor of C => A ancestor of C.

        Ref: dag.dfy IsAncestor (reflexive-transitive closure)
        """
        self.assertIn(self.A, self.chain.ancestors_inclusive(self.C))

    def test_descendant_reflexive(self):
        """Every node is its own descendant.

        Ref: dag.dfy Descendants definition
        """
        for node in [self.A, self.B, self.C]:
            self.assertIn(node, self.chain.descendants_inclusive(node))

    def test_descendant_transitive(self):
        """Descendancy is transitive.

        Ref: dag.dfy Descendants definition
        """
        self.assertIn(self.C, self.chain.descendants_inclusive(self.A))

    def test_ancestors_of_chain_endpoint(self):
        """Ancestors(G, {C}) = {A, B, C} in the chain graph.

        Ref: dag.dfy Ancestors ghost function
        """
        self.assertEqual(
            {self.A, self.B, self.C},
            self.chain.ancestors_inclusive(self.C),
        )

    def test_descendants_of_chain_start(self):
        """Descendants(G, {A}) = {A, B, C} in the chain graph.

        Ref: dag.dfy Descendants ghost function
        """
        self.assertEqual(
            {self.A, self.B, self.C},
            self.chain.descendants_inclusive(self.A),
        )

    def test_chain_is_dag(self):
        """The chain graph is a DAG.

        Ref: dag.dfy IsDAG, ChainGraph_IsDAG
        """
        self.assertTrue(self.chain.is_acyclic())

    def test_topological_sort_valid(self):
        """A DAG admits a topological sort where parents precede children.

        Ref: dag.dfy IsTopologicalSort
        """
        order = self.chain.topological_sort()
        self.assertEqual(3, len(order))
        self.assertLess(order.index(self.A), order.index(self.B))
        self.assertLess(order.index(self.B), order.index(self.C))

    def test_non_descendants(self):
        """NonDescendants(G, B) = {A}.

        Ref: dag.dfy NonDescendants
        """
        result = self.chain.non_descendants(self.B)
        self.assertEqual({self.A}, result)

    def test_non_descendants_of_source(self):
        """NonDescendants(G, A) = {} since A is the root.

        Ref: dag.dfy NonDescendants
        """
        result = self.chain.non_descendants(self.A)
        self.assertEqual(set(), result)


class TestDSeparation(unittest.TestCase):
    """Tests corresponding to dag.dfy §6 d-Separation."""

    def setUp(self) -> None:
        """Build the three-node chain A -> B -> C from dag.dfy §9."""
        self.A = Variable("A")
        self.B = Variable("B")
        self.C = Variable("C")
        self.chain = NxMixedGraph.from_edges(
            directed=[(self.A, self.B), (self.B, self.C)]
        )

    def test_chain_a_indep_c_given_b(self):
        """A ⊥ C | {B} in chain A->B->C.

        Ref: dag.dfy Chain_A_indep_C_given_B
        """
        judgement = are_d_separated(self.chain, self.A, self.C, conditions=[self.B])
        self.assertTrue(judgement.separated)

    def test_chain_a_not_indep_c_unconditional(self):
        """A is NOT d-separated from C unconditionally in A->B->C.

        Ref: dag.dfy (negative case — no conditioning blocks the path)
        """
        judgement = are_d_separated(self.chain, self.A, self.C)
        self.assertFalse(judgement.separated)

    def test_dsep_symmetry(self):
        """(Y ⊥ Z | W) => (Z ⊥ Y | W).

        Ref: dag.dfy:261 DSep_Symmetry
        """
        j1 = are_d_separated(self.chain, self.A, self.C, conditions=[self.B])
        j2 = are_d_separated(self.chain, self.C, self.A, conditions=[self.B])
        self.assertEqual(j1.separated, j2.separated)


class TestSemiGraphoidAxioms(unittest.TestCase):
    """Tests for semi-graphoid axioms. Ref: dag.dfy §7."""

    def setUp(self) -> None:
        """Build a 4-node chain A->B->C->D for richer d-separation testing."""
        self.A = Variable("A")
        self.B = Variable("B")
        self.C = Variable("C")
        self.D = Variable("D")
        self.chain4 = NxMixedGraph.from_edges(
            directed=[(self.A, self.B), (self.B, self.C), (self.C, self.D)]
        )

    def test_decomposition(self):
        """(Y ⊥ Z ∪ Z' | W) => (Y ⊥ Z | W).

        Chain A->B->C->D: B blocks all paths from A to C and D.
        Ref: dag.dfy:266 DSep_Decomposition
        """
        j_c = are_d_separated(self.chain4, self.A, self.C, conditions=[self.B])
        j_d = are_d_separated(self.chain4, self.A, self.D, conditions=[self.B])
        self.assertTrue(j_c.separated, "Decomposition: A ⊥ C | {B}")
        self.assertTrue(j_d.separated, "Decomposition: A ⊥ D | {B}")

    def test_weak_union(self):
        """(Y ⊥ Z ∪ Z' | W) => (Y ⊥ Z | W ∪ Z').

        Chain A->B->C->D: A ⊥ C | {B} => A ⊥ C | {B, D}.
        Ref: dag.dfy:273 DSep_WeakUnion
        """
        j_base = are_d_separated(self.chain4, self.A, self.C, conditions=[self.B])
        self.assertTrue(j_base.separated)
        j_weak = are_d_separated(self.chain4, self.A, self.C, conditions=[self.B, self.D])
        self.assertTrue(j_weak.separated, "Weak union: A ⊥ C | {B, D}")

    def test_contraction(self):
        """(Y ⊥ Z | W ∪ Z') ∧ (Y ⊥ Z' | W) => (Y ⊥ Z ∪ Z' | W).

        Chain A->B->C->D: premises A ⊥ D | {B,C} and A ⊥ C | {B}.
        Ref: dag.dfy:280 DSep_Contraction
        """
        j1 = are_d_separated(self.chain4, self.A, self.D, conditions=[self.B, self.C])
        j2 = are_d_separated(self.chain4, self.A, self.C, conditions=[self.B])
        self.assertTrue(j1.separated, "Premise 1: A ⊥ D | {B, C}")
        self.assertTrue(j2.separated, "Premise 2: A ⊥ C | {B}")
        j3 = are_d_separated(self.chain4, self.A, self.D, conditions=[self.B])
        self.assertTrue(j3.separated, "Contraction: A ⊥ D | {B}")


class TestLocalMarkov(unittest.TestCase):
    """Tests for the Local Markov Property. Ref: dag.dfy §8."""

    def test_local_markov_chain(self):
        """Every node v: {v} ⊥ (NonDesc(v) minus Pa(v)) | Pa(v).

        Nodes that are both non-descendants and parents are already conditioned
        on, so they are excluded from the d-separation query.
        Ref: dag.dfy:311 LocalMarkov
        """
        A, B, C = Variable("A"), Variable("B"), Variable("C")
        chain = NxMixedGraph.from_edges(directed=[(A, B), (B, C)])
        for node in [A, B, C]:
            non_desc = chain.non_descendants(node)
            parents = set(chain.directed.predecessors(node))
            for nd in non_desc - parents:
                judgement = are_d_separated(chain, node, nd, conditions=parents)
                self.assertTrue(
                    judgement.separated,
                    f"Local Markov violated: {node} not d-sep from {nd} given {parents}",
                )


class TestDoCalculusRules(unittest.TestCase):
    """Tests corresponding to do_calculus.dfy §4-7."""

    def test_rule_1_does_not_apply_chain(self):
        """Rule 1 does NOT apply: M is not d-sep from Y given X in G_{X̄}.

        Graph: X->M->Y with do(X). G_{X̄} same (X is source).
        (Y ⊥ M | {X}) fails because the path M->Y remains active.
        Ref: do_calculus.dfy:118 Rule1_InsertDeleteObservation
        """
        X, M, Y = Variable("X"), Variable("M"), Variable("Y")
        graph = NxMixedGraph.from_edges(directed=[(X, M), (M, Y)])
        self.assertFalse(
            rule_1_of_do_calculus_applies(
                graph, treatments={X}, outcomes={Y}, conditions=set(), observation=M,
            )
        )

    def test_rule_1_applies_isolated_node(self):
        """Rule 1 applies: Z is d-sep from Y given X in G_{X̄}.

        Graph: X->Y, X->Z. Z and Y share parent X only.
        After removing in-edges of X: X, Y, Z all have no edges.
        Y ⊥ Z | X (conditioning on X, the path Y<-X->Z is blocked).
        Ref: do_calculus.dfy:118 Rule1_InsertDeleteObservation
        """
        X, Y, Z = Variable("X"), Variable("Y"), Variable("Z")
        graph = NxMixedGraph.from_edges(directed=[(X, Y), (X, Z)])
        self.assertTrue(
            rule_1_of_do_calculus_applies(
                graph, treatments={X}, outcomes={Y}, conditions=set(), observation=Z,
            )
        )

    def test_rule_2_chain(self):
        """Rule 2: action/observation exchange on a chain.

        Graph: X->Z->Y. Check condition in G_{X̄, Z̲}.
        Ref: do_calculus.dfy:132 Rule2_ActionObservationExchange
        """
        X, Z, Y = Variable("X"), Variable("Z"), Variable("Y")
        graph = NxMixedGraph.from_edges(directed=[(X, Z), (Z, Y)])
        # G_{X̄} = same (X is source). G_{X̄, Z̲} = remove Z's outgoing.
        # In G_{X̄, Z̲}: X->Z, Y isolated. (Y ⊥ Z | {X}) holds.
        self.assertTrue(
            rule_2_of_do_calculus_applies(
                graph, treatments={X}, outcomes={Y}, conditions={Z}, condition=Z,
            )
        )

    def test_rule_3_isolated_action(self):
        """Rule 3: do(Z) deletable when Z has no path to Y after mutilation.

        Graph: X->Y, X->Z. Z not ancestor of W={} (empty conditions).
        G_{X̄}: same (X is source). G_{X̄,Z̄}: remove Z's in-edges (X->Z gone).
        In G_{X̄,Z̄}: only X->Y; Y ⊥ Z | X holds.
        Ref: do_calculus.dfy:149 Rule3_InsertDeleteAction
        """
        X, Y, Z = Variable("X"), Variable("Y"), Variable("Z")
        graph = NxMixedGraph.from_edges(directed=[(X, Y), (X, Z)])
        self.assertTrue(
            rule_3_of_do_calculus_applies(
                graph, treatments={X}, outcomes={Y}, conditions=set(), action=Z,
            )
        )

    def test_backdoor_simple(self):
        """Z satisfies backdoor when it blocks backdoor paths and is not a descendant of X.

        Graph: Z->X->Y, Z->Y.
        Ref: do_calculus.dfy:189 BackdoorAdjustment
        """
        X, Y, Z = Variable("X"), Variable("Y"), Variable("Z")
        graph = NxMixedGraph.from_edges(directed=[(Z, X), (X, Y), (Z, Y)])
        self.assertTrue(satisfies_backdoor(graph, outcomes={Y}, treatments={X}, adjustment={Z}))

    def test_backdoor_fails_descendant(self):
        """Backdoor fails when adjustment set contains a descendant of X.

        Graph: X->M->Y. M is a descendant of X.
        Ref: do_calculus.dfy:189 BackdoorAdjustment
        """
        X, M, Y = Variable("X"), Variable("M"), Variable("Y")
        graph = NxMixedGraph.from_edges(directed=[(X, M), (M, Y)])
        self.assertFalse(satisfies_backdoor(graph, outcomes={Y}, treatments={X}, adjustment={M}))

    def test_frontdoor_classic(self):
        """M satisfies frontdoor for X->Y with confounding X<->Y.

        Graph: X->M->Y, X<->Y (bidirected).
        Ref: do_calculus.dfy:211 FrontdoorCriterion
        """
        X, M, Y = Variable("X"), Variable("M"), Variable("Y")
        graph = NxMixedGraph.from_edges(
            directed=[(X, M), (M, Y)],
            undirected=[(X, Y)],
        )
        self.assertTrue(
            satisfies_frontdoor(graph, outcomes={Y}, treatments={X}, mediators={M})
        )

    def test_frontdoor_fails_no_mediator(self):
        """Frontdoor fails with empty mediator set and direct confounding.

        Graph: X->Y, X<->Y.
        Ref: do_calculus.dfy:211 FrontdoorCriterion
        """
        X, Y = Variable("X"), Variable("Y")
        graph = NxMixedGraph.from_edges(
            directed=[(X, Y)],
            undirected=[(X, Y)],
        )
        self.assertFalse(
            satisfies_frontdoor(graph, outcomes={Y}, treatments={X}, mediators=set())
        )


class TestProbabilityAxioms(unittest.TestCase):
    """Tests aligning y0 DSL with probability.dfy axioms."""

    def test_chain_rule_two_vars(self):
        """P(A, B) = P(A | B) * P(B).

        Ref: probability.dfy:151 ChainRule
        """
        from y0.dsl import A, B, P
        from y0.mutate.chain import chain_expand

        result = chain_expand(P(A, B))
        expected = P(A | B) * P(B)
        self.assertEqual(expected, result)

    def test_chain_rule_three_vars(self):
        """P(A, B, C) = P(A | B, C) * P(B | C) * P(C).

        Ref: probability.dfy:151 ChainRule (iterated)
        """
        from y0.dsl import A, B, C, P
        from y0.mutate.chain import chain_expand

        result = chain_expand(P(A, B, C))
        expected = P(A | B, C) * P(B | C) * P(C)
        self.assertEqual(expected, result)

    def test_bayes_theorem(self):
        """P(A | B) = P(A, B) / Sum_A P(A, B).

        bayes_expand() uses the marginalization form, which is equivalent to
        P(B|A)*P(A)/P(B) but expressed via Sum.
        Ref: probability.dfy:165 BayesTheorem
        """
        from y0.dsl import A, B, P, Sum
        from y0.mutate.chain import bayes_expand

        result = bayes_expand(P(A | B))
        expected = P(A, B) / Sum[A](P(A, B))
        self.assertEqual(expected, result)


class TestAlgebraicIdentities(unittest.TestCase):
    """Tests for algebraic consequences of Kolmogorov axioms on the symbolic DSL.

    The Dafny spec defines Kolmogorov axioms over numerical PMFs.
    These tests verify the algebraic identities that the symbolic
    DSL must satisfy as consequences of those axioms.
    Ref: probability.dfy §§2-5, 9.
    """

    def test_one_is_multiplicative_identity_left(self):
        """One() * P(A) == P(A).

        Ref: probability.dfy:81 Axiom_Normalization (algebraic consequence)
        """
        from y0.dsl import A, One, P

        self.assertEqual(P(A), One() * P(A))

    def test_one_is_multiplicative_identity_right(self):
        """P(A, B) * One() == P(A, B).

        Ref: probability.dfy:81 Axiom_Normalization (algebraic consequence)
        """
        from y0.dsl import A, B, One, P

        self.assertEqual(P(A, B), P(A, B) * One())

    def test_zero_is_absorbing_left(self):
        """Zero() * P(A, B) == Zero().

        Ref: probability.dfy:103 EmptyEventZero (algebraic consequence)
        """
        from y0.dsl import A, B, P, Zero

        self.assertEqual(Zero(), Zero() * P(A, B))

    def test_zero_is_absorbing_right(self):
        """P(A, B) * Zero() == Zero().

        Ref: probability.dfy:103 EmptyEventZero (algebraic consequence)
        """
        from y0.dsl import A, B, P, Zero

        self.assertEqual(Zero(), P(A, B) * Zero())

    def test_zero_divided_by_nonzero(self):
        """Zero() / P(A) == Zero().

        Ref: probability.dfy:103 EmptyEventZero (algebraic consequence)
        """
        from y0.dsl import A, P, Zero

        self.assertEqual(Zero(), Zero() / P(A))

    def test_joint_commutativity_two_vars(self):
        """P(A, B) == P(B, A).

        Ref: probability.dfy:226 Independent_Symmetric (joint commutativity)
        """
        from y0.dsl import A, B, P

        self.assertEqual(P(A, B), P(B, A))

    def test_joint_commutativity_three_vars(self):
        """P(A, B, C) == P(C, A, B) (any permutation).

        Ref: probability.dfy:226 Independent_Symmetric (joint commutativity)
        """
        from y0.dsl import A, B, C, P

        self.assertEqual(P(A, B, C), P(C, A, B))

    def test_conditional_child_commutativity(self):
        """P(A, B | C) == P(B, A | C).

        Ref: probability.dfy:211 CondIndep_Symmetric (conditional commutativity)
        """
        from y0.dsl import A, B, C, P

        self.assertEqual(P(A & B | C), P(B & A | C))


# ── Implementation stubs needed ──
# The following methods/functions must exist for these tests to pass:
#   - is_acyclic
#   - non_descendants
